done
Raventwd/OOPPolymorphism pull request #1
Opened 2023-01-26 17:37 UTC by Raventwd

2023-01-30 18:20 UTC, OlgaLugacheva requested changes

2023-01-30 18:20 UTC, OlgaLugacheva commented on src/Bus.java
> +    enum sitCapacity{
перечисление лучше выносить в отдельный класс и лучше не использовать в коде кириллицу - а перечисления - это часть кода

2023-01-30 18:20 UTC, OlgaLugacheva commented on src/Heavyweightcar.java
> +    allowedWeight allowedWeight;
модификатор доступа забыт

2023-01-30 18:20 UTC, OlgaLugacheva commented on src/Lightweightcar.java
> +        Минивэн
никакой кириллицы

2023-02-07 08:30 UTC, zrazzhivin commented on src/maintenanceStation.java
> +public class maintenanceStation {
классы именуем с заглавной буквы, не с прописной.

2023-02-07 08:31 UTC, zrazzhivin commented on src/maintenanceStation.java
> +    public void addCarToQueue(Queue queue){
такая реализация не пойдет. Попробуй перечитать требования к станции. 
Очередь - это свойство станции. Почему пользователь должен сам передавать очередь в аргументах? 
В очереди мы хотим хранить транспорт. Ты создал строковую машину - это как?

2023-02-07 08:31 UTC, zrazzhivin commented on src/maintenanceStation.java
> +    public void maintenance(){
что полезного делает этот метод, кроме того, как печатает в консоль сообщение? В чем заключается работа станции?

2023-02-07 08:31 UTC, zrazzhivin commented on src/Transport.java
> +    private Mechanic mechanic;
по условию задачи нужно хранить список механиков

2023-02-07 08:32 UTC, zrazzhivin commented on src/Main.java
> +    public static void main(String[] args)  {
в мейне нужно проверить все то, что ты добавил в задании

2023-02-11 11:54 UTC, zrazzhivin commented on src/MaintenanceStation.java
> +    public void queueCarAdd() {
этот метод должен принимать аргумент типа Transport - как пользователь будет использовать твою станцию, если он не может добавить в очередь желаемый объект? 
В теле метода просто добавляем его в очередь

2023-02-11 11:55 UTC, zrazzhivin commented on src/MaintenanceStation.java
> +    public Queue<Object> getCarsQueue() {
этот метод должен проводить диагностику (вызывать метод диагностику) и первого элемента из очереди. 
Нет необходимости пользователю возвращать всю очередь.

2023-02-21 13:26 UTC, closed without merging